language: node_js
sudo: false
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_8926b8c4a31e_key -iv $encrypted_8926b8c4a31e_iv
  -in ssh_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- npm install hexo-cli -g
- npm install gulp -g
- npm install -d --save gulp gulp-clean gulp-load-plugins gulp-minify-css gulp-minify-html gulp-rename gulp-uglify gulp-shell

script:
- hexo clean
- hexo generate
- gulp
- cd dst
- git init
- git config user.name "ahjsrhj"
- git config user.email aha199277@qq.com
- git add .
- git commit -m "Update docs"
- git remote add origin git@github.com:ahjsrhj/ahjsrhj.github.io.git
- git push -f origin master

branches:
  only:
    - blog
