menu:
    Blog: /
    Archive: /archives/
    About: /about/
    Game: /game/
    # Weibo: http://weibo.com/sunchongsheng
    GITHUB: https://github.com/ahjsrhj
    # RSS: /atom.xml
    FRIEND: /friend/

favicon: https://i.loli.net/2018/09/30/5bb06e7c3a31e.png
logo: https://i.loli.net/2018/09/30/5bb06e8ed7771.png

# Comment
# e.g disqus: seansun
# disqus: hexer
# duoshuo:
valine: true

# Analytics
# google-analytics:
ga: UA-109294877-1

# Copyright Infomation
startyear: 2015
